name: Typing Checks

on:
  push:
    # IMPORTANT: update these paths when we expand type-checking coverage
    branches: [main]
    paths:
      - 'jupyter_server_documents/rooms/**'
      - '.github/workflows/typing-checks.yml'
  pull_request:
    branches: [main]
    paths:
      - 'jupyter_server_documents/rooms/**'
      - '.github/workflows/typing-checks.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python:
    name: 'Python'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install mypy
          python -m pip install -e .[test]

      - name: Type-check `rooms` module
        run: |
          mypy jupyter_server_documents/rooms
